-- Run this in Supabase SQL Editor to align tables with the bot.
-- If columns already exist, you'll get "already exists" errors — that's OK, skip those lines.

-- ─── users table: add missing columns (if you only have user_id, username, full_name, language, currency, created_at)
ALTER TABLE public.users
  ADD COLUMN IF NOT EXISTS last_active timestamptz,
  ADD COLUMN IF NOT EXISTS comparison_count integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS click_history jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS last_click jsonb;

-- Ensure user_id is primary key (optional; run only if not already set)
-- ALTER TABLE public.users ADD PRIMARY KEY (user_id);

-- ─── rate_alerts: required columns (create table if missing)
CREATE TABLE IF NOT EXISTS public.rate_alerts (
  user_id bigint NOT NULL,
  currency text NOT NULL,
  target_rate double precision NOT NULL,
  lang text DEFAULT 'en',
  created_at timestamptz DEFAULT now(),
  PRIMARY KEY (user_id, currency)
);

-- ─── referral_clicks: required columns (create table if missing)
CREATE TABLE IF NOT EXISTS public.referral_clicks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id_hash text NOT NULL,
  platform text NOT NULL,
  amount_krw integer NOT NULL,
  currency text NOT NULL,
  click_type text DEFAULT 'actual',
  clicked_at timestamptz DEFAULT now(),
  date date
);
