-- Run this entire script in Supabase SQL Editor (Dashboard → SQL Editor → New Query)

-- ─── users ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.users (
  user_id          bigint PRIMARY KEY,
  username         text,
  full_name        text,
  language         text DEFAULT 'en',
  currency         text DEFAULT 'NPR',
  created_at       timestamptz DEFAULT now(),
  last_active      timestamptz DEFAULT now(),
  comparison_count integer DEFAULT 0,
  click_history    jsonb DEFAULT '[]'::jsonb,
  last_click       jsonb,
  platform         text
);

-- ─── rate_alerts ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.rate_alerts (
  user_id     bigint NOT NULL,
  currency    text NOT NULL,
  target_rate double precision NOT NULL,
  lang        text DEFAULT 'en',
  created_at  timestamptz DEFAULT now(),
  PRIMARY KEY (user_id, currency)
);

-- ─── referral_clicks ──────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.referral_clicks (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id_hash text NOT NULL,
  platform     text NOT NULL,
  amount_krw   integer NOT NULL,
  currency     text NOT NULL,
  click_type   text DEFAULT 'actual',
  clicked_at   timestamptz DEFAULT now(),
  date         date
);
